// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsdb.proto

/*
Package tsdb is a generated protocol buffer package.

It is generated from these files:
	tsdb.proto

It has these top-level messages:
	Key
	TimeValuePair
	DataPoint
	DataPoints
	PutRequest
	PutResponse
	GetRequest
	GetResponse
*/
package tsdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Key struct {
	Key     []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ShardId int32  `protobuf:"varint,2,opt,name=shardId" json:"shardId,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Key) GetShardId() int32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

type TimeValuePair struct {
	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *TimeValuePair) Reset()                    { *m = TimeValuePair{} }
func (m *TimeValuePair) String() string            { return proto.CompactTextString(m) }
func (*TimeValuePair) ProtoMessage()               {}
func (*TimeValuePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimeValuePair) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimeValuePair) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DataPoint struct {
	Key   *Key           `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *TimeValuePair `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *DataPoint) Reset()                    { *m = DataPoint{} }
func (m *DataPoint) String() string            { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()               {}
func (*DataPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DataPoint) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataPoint) GetValue() *TimeValuePair {
	if m != nil {
		return m.Value
	}
	return nil
}

type DataPoints struct {
	Key    *Key             `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values []*TimeValuePair `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *DataPoints) Reset()                    { *m = DataPoints{} }
func (m *DataPoints) String() string            { return proto.CompactTextString(m) }
func (*DataPoints) ProtoMessage()               {}
func (*DataPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DataPoints) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataPoints) GetValues() []*TimeValuePair {
	if m != nil {
		return m.Values
	}
	return nil
}

type PutRequest struct {
	Datas []*DataPoint `protobuf:"bytes,1,rep,name=datas" json:"datas,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutRequest) GetDatas() []*DataPoint {
	if m != nil {
		return m.Datas
	}
	return nil
}

type PutResponse struct {
	N int32 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PutResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetRequest struct {
	Keys  []*Key `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Begin int64  `protobuf:"varint,2,opt,name=begin" json:"begin,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetRequest) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetRequest) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *GetRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type GetResponse struct {
	Datas []*DataPoints `protobuf:"bytes,1,rep,name=datas" json:"datas,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetResponse) GetDatas() []*DataPoints {
	if m != nil {
		return m.Datas
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "tsdb.Key")
	proto.RegisterType((*TimeValuePair)(nil), "tsdb.TimeValuePair")
	proto.RegisterType((*DataPoint)(nil), "tsdb.DataPoint")
	proto.RegisterType((*DataPoints)(nil), "tsdb.DataPoints")
	proto.RegisterType((*PutRequest)(nil), "tsdb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "tsdb.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "tsdb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "tsdb.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tsdb service

type TsdbClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type tsdbClient struct {
	cc *grpc.ClientConn
}

func NewTsdbClient(cc *grpc.ClientConn) TsdbClient {
	return &tsdbClient{cc}
}

func (c *tsdbClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/tsdb.Tsdb/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsdbClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/tsdb.Tsdb/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tsdb service

type TsdbServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterTsdbServer(s *grpc.Server, srv TsdbServer) {
	s.RegisterService(&_Tsdb_serviceDesc, srv)
}

func _Tsdb_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsdbServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsdb.Tsdb/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsdbServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsdb_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsdbServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsdb.Tsdb/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsdbServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tsdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tsdb.Tsdb",
	HandlerType: (*TsdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Tsdb_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Tsdb_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsdb.proto",
}

func init() { proto.RegisterFile("tsdb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x97, 0x65, 0xdd, 0xcb, 0x4e, 0xf7, 0xf2, 0xee, 0x8d, 0x5e, 0x14, 0xa7, 0x30, 0x02,
	0xca, 0x44, 0x19, 0xb8, 0xe1, 0x27, 0x50, 0x18, 0xb2, 0x9b, 0x92, 0x8d, 0xdd, 0xa7, 0xf4, 0xa0,
	0x65, 0xae, 0x9d, 0x4b, 0x2a, 0xf4, 0xdb, 0x4b, 0x92, 0xfe, 0x9b, 0xa0, 0x77, 0xe7, 0x9c, 0x3c,
	0xcf, 0xef, 0x3c, 0x49, 0x0b, 0xa0, 0x55, 0x1c, 0xcd, 0x0e, 0xc7, 0x4c, 0x67, 0xac, 0x67, 0x6a,
	0xfe, 0x00, 0x74, 0x85, 0x05, 0x1b, 0x01, 0xdd, 0x61, 0x11, 0x90, 0x09, 0x99, 0x0e, 0x85, 0x29,
	0x59, 0x00, 0x7f, 0xd4, 0x9b, 0x3c, 0xc6, 0x2f, 0x71, 0xd0, 0x9d, 0x90, 0xa9, 0x27, 0xaa, 0x96,
	0x3f, 0xc1, 0xdf, 0x4d, 0xb2, 0xc7, 0xad, 0x7c, 0xcf, 0x31, 0x94, 0xc9, 0x91, 0x5d, 0xc2, 0x40,
	0x27, 0x7b, 0x54, 0x5a, 0xee, 0x0f, 0x16, 0x41, 0x45, 0x33, 0x60, 0xe7, 0xe0, 0x7d, 0x1a, 0xa9,
	0xc5, 0x10, 0xe1, 0x1a, 0xbe, 0x86, 0xc1, 0xb3, 0xd4, 0x32, 0xcc, 0x92, 0x54, 0xb3, 0x71, 0xb3,
	0xdd, 0x9f, 0x0f, 0x66, 0x36, 0xe4, 0x0a, 0x0b, 0x17, 0xe4, 0xb6, 0xed, 0xf7, 0xe7, 0x67, 0xee,
	0xf8, 0x24, 0x41, 0x05, 0xdd, 0x02, 0xd4, 0x50, 0xf5, 0x3b, 0xf5, 0x0e, 0xfa, 0xd6, 0xa3, 0x82,
	0xee, 0x84, 0xfe, 0x84, 0x2d, 0x25, 0x7c, 0x01, 0x10, 0xe6, 0x5a, 0xe0, 0x47, 0x8e, 0x4a, 0xb3,
	0x6b, 0xf0, 0x62, 0xa9, 0xa5, 0x0a, 0x88, 0x75, 0xfe, 0x73, 0xce, 0x7a, 0xb1, 0x70, 0xa7, 0x7c,
	0x0c, 0xbe, 0x35, 0xa9, 0x43, 0x96, 0x2a, 0x64, 0x43, 0x20, 0xa9, 0xcd, 0xe2, 0x09, 0x92, 0xf2,
	0x35, 0xc0, 0x12, 0x6b, 0xe2, 0x15, 0xf4, 0x76, 0x58, 0x54, 0xc0, 0x56, 0x54, 0x3b, 0x36, 0x2f,
	0x18, 0xe1, 0x6b, 0x92, 0xda, 0x17, 0xa0, 0xc2, 0x35, 0xe6, 0x93, 0x61, 0x1a, 0x07, 0xd4, 0xce,
	0x4c, 0xc9, 0x1f, 0xc1, 0xb7, 0xd0, 0x72, 0xe3, 0xcd, 0x69, 0xce, 0xd1, 0xb7, 0x9c, 0xaa, 0x0c,
	0x3a, 0x8f, 0xa0, 0xb7, 0x51, 0x71, 0xc4, 0xee, 0x81, 0x86, 0xb9, 0x66, 0xa5, 0xae, 0xb9, 0xf0,
	0xc5, 0xff, 0xd6, 0xc4, 0xb1, 0x79, 0xc7, 0xa8, 0x97, 0x58, 0xab, 0x9b, 0xcb, 0x54, 0xea, 0x56,
	0x12, 0xde, 0x89, 0xfa, 0xf6, 0x9f, 0x5b, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x13, 0xbb,
	0x9b, 0x81, 0x02, 0x00, 0x00,
}
